<h2><?php echo $this->escape($this->title); ?></h2>

<table class="table">
	<thead>
	<td>Produkt</td>
	<td>Množství</td>
	<td>Cena</td>
	</thead>
	<?php $sum = 0; ?>
<?php foreach ($this->products as $product) { ?>
	<tr>
		<td>
			<?php echo $this->escape($product['name']); ?>
		</td>
		<td>
			<?php echo $this->escape($product['amount']) . ' ' . $this->escape($product['unit']); ?>
		</td>
		<td>
			<?php echo $this->escape($product['unit_price'] * $product['amount']); ?> Kč
			<?php $sum += ($this->escape($product['unit_price'] * $product['amount'])); ?>
		</td>
	</tr>
<?php } ?>
	<tr>
		<td colspan="2">
			<b>Celkem</b>
		</td>
		<td>
			<b><?php echo $this->escape($sum); ?> Kč</b>
		</td>
	</tr>
</table>
