<div class="container">
	<h2><?php echo $this->escape($this->title); ?></h2>
	<div class="container-fluid">
		<?php foreach ($this->products as $product) { ?>
			<div class="list-group product" >
				<a href="<?php echo $this->url(
					array('controller' => 'sell',
						'action' => 'add',
						'id' => $product->getId()),
					'default',
					true) ?>" class="list-group-item product-text <?php if ($product->count <= 0) echo 'disabled'; ?>"
				>
					<?php echo $this->escape($product->getName()) . ': ' . $this->escape($product->getPrice() . ' Kč'); ?>
				</a>
			</div>
		<?php } ?>
	</div>
</div>
<div>
