<h2><?php echo $this->escape($this->title); ?></h2>

<a href="<?php echo $this->url(
				array('controller' => 'sell', 'action' => 'done', 'saleId' => $this->saleId),
				'default', true) ?>" class="submit btn btn-lg btn-success btn-block <?php if (count($this->products) <= 0) echo 'disabled'; ?>">Dokončit prodej</a>
<a href="<?php echo $this->url(
				array('controller' => 'sell', 'action' => 'index', 'saleId' => $this->saleId),
				'default', true) ?>" class="submit btn btn-lg btn-primary btn-block">Přidat produkt</a>
<a href="<?php echo $this->url(
				array('controller' => 'sell', 'action' => 'cancel', 'saleId' => $this->saleId),
				'default', true) ?>" class="submit btn btn-lg btn-danger btn-block">Zrušit prodej</a>
<br>

<table class="table">
	<thead>
	<td>Produkt</td>
	<td>Množství</td>
	<td>Cena</td>
	<td>Akce</td>
	</thead>
<?php foreach ($this->products as $product) { ?>
	<tr>
		<td>
			<?php echo $this->escape($product['name']); ?>
		</td>
		<td>
			<?php echo $this->escape($product['amount']) . ' ' . $this->escape($product['unit']); ?>
		</td>
		<td>
			<?php echo $this->escape($product['unit_price'] * $product['amount']); ?>
		</td>
		<td>
			<a href="<?php echo $this->url(
				array('controller' => 'sell', 'action' => 'remove', 'saleId' => $this->saleId, 'salesProductsId' => $product['sales_products_id']),
				'default', true) ?>" class="btn btn-danger">X</a>
		</td>
	</tr>
<?php } ?>
</table>
