<h2><?php echo $this->escape($this->title); ?></h2>

<br>
<table class="table">
	<thead>
	<td>Produkt</td>
	<td>Množství</td>
	<td>Cena</td>
	</thead>
<?php foreach ($this->products as $product) { ?>
	<tr>
		<td>
			<?php echo $this->escape($product['name']); ?>
		</td>
		<td>
			<?php echo $this->escape($product['amount']) . ' ' . $this->escape($product['unit']); ?>
		</td>
		<td>
			<?php echo $this->escape($product['unit_price'] * $product['amount']); ?>
		</td>
	</tr>
<?php } ?>
</table>

<p>Prodej č. : <?php echo $this->sale->getId(); ?></p>
<p>Datum: <?php echo $this->sale->getDate(); ?></p>
