<nav class="navbar navbar-default">
    <div class="container-fluid">
    	<?php
    		if (Zend_Auth::getInstance()->hasIdentity()) {
    	?>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="visible-xs pull-right new-sell-menu btn btn-success" href="<?php echo $this->url(
                        array('controller' => 'sell'),
                        'default',
                        true) ?>">
                    Nový prodej
                </a>
                <a class="navbar-brand" href="<?php echo $this->url(
                        array('controller' => 'home'),
                        'default',
                        true) ?>">EET</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        		<ul class="nav navbar-nav">
        			<li role="presentation" class="right">
        				<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        					Prodej <span class="caret"></span>
        				</a>
        				<ul class="dropdown-menu right">
        					<li role="presentation" >
        						<a href="<?php echo $this->url(
        								array('controller' => 'sell'),
        								'default',
        								true) ?>">
        							Nový prodej
        						</a>
        					</li>
        					<li role="presentation" >
        						<a href="<?php echo $this->url(
        								array('controller' => 'sell', 'action' => 'sold-list'),
        								'default',
        								true) ?>">
        							Vystavené paragony
        						</a>
        					</li>
        				</ul>
        			</li>
        			<li role="presentation" >
        				<a href="<?php echo $this->url(
        					array('controller' => 'product'),
        					'default',
        					true) ?>">
        					Produkty
        				</a>
        			</li>
        			<li role="presentation" >
        				<a href="<?php echo $this->url(
        						array('controller' => 'warehouse'),
        						'default',
        						true) ?>">
        					Sklad
        				</a>
        			</li>
        			<li role="presentation" class="right">
        				<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        					Nastavení <span class="caret"></span>
        				</a>
        				<ul class="dropdown-menu right">
        					<li role="presentation" >
        						<a href="<?php echo $this->url(
        							array('controller' => 'user', 'action' => 'edit'),
        							'default',
        							true) ?>">
        							Osobních údajů
        						</a>
        					</li>
        					<li role="presentation" >
        						<a href="<?php echo $this->url(
        							array('controller' => 'store'),
        							'default',
        							true) ?>">
        							Prodejního místa
        						</a>
        					</li>
        				</ul>
        			</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
        			<li role="presentation" class="navbar-right">
        				<a href="<?php echo $this->url(
        						array('controller' => 'index'),
        						'logout',
        						true) ?>">
        					Odhlásit se
        				</a>
        			</li>
        		</ul>
            </div>
    	<?php
    		}
    	?>
    </div>
</nav>
