<div class="header">

	<ul class="nav nav-tabs">
		<li role="presentation" >
			<a href="<?php echo $this->url(
				array('controller' => 'home'),
				'default',
				true) ?>">
				Domů
			</a>
		</li>
		<li role="presentation" >
			<a href="<?php echo $this->url(
				array('controller' => 'product'),
				'default',
				true) ?>">
				Produkty
			</a>
		</li>
		<li role="presentation" >
			<a href="#">
				Nastavení
			</a>
		</li>
	</ul>
</div>
