<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title><?php echo $this->title; ?></title>
		<meta name="description" content="EET">
		<meta name="author" content="Tym 7">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/global.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/products.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/forms.css">
	</head>
	
	<body>

		<div class="container">

			<?php echo $this->render('header.phtml') ?>

			<?php
			$messages = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->getMessages();
			if (count($messages) > 0) {
				echo '<br>';
				foreach ($messages as $message) {
					echo '<div class="alert alert-info">'.$message.'</div>';
				}
			}
			?>

			<?php echo $this->layout()->content; ?>
		</div>

		<script src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js"></script>
		<script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js"></script>
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</body>

</html>

