<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="jumbotron">
			<h1>Oops, 404!</h1>
			<p>Stránka bohužel nebyla nalezena.</p>
			<p>
				<a class="btn btn-primary btn-lg" href="<?php echo $this->url(['controller' => 'index'], 'default', true) ?>" role="button">
					Pokračovat na úvodní stránku.
				</a>
			</p>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>
